image: node:latest

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - cd doc
    - yarn install
    - yarn build:gitlab
    - rm -rf ../public
    - mv public ../
  artifacts:
      paths:
        - public
  only:
    - master
    # - main

